import SpotifyWebApi from "spotify-web-api-node";

import { adminDb } from "@/lib/firebase/admin";
import { verifyUser } from "@/lib/firebase/verify";

type SongInput = { title: string; artist: string };

export async function POST(request: Request) {
  try {
    const uid = await verifyUser(request.headers.get("authorization"));
    const { playlistName, songs } = await request.json();

    if (!playlistName || !Array.isArray(songs)) {
      return Response.json({ error: "Missing payload" }, { status: 400 });
    }

    const clientId = process.env.SPOTIFY_CLIENT_ID;
    const clientSecret = process.env.SPOTIFY_CLIENT_SECRET;
    const redirectUri = process.env.NEXT_PUBLIC_SPOTIFY_REDIRECT_URI;

    if (!clientId || !clientSecret || !redirectUri) {
      return Response.json(
        { error: "Missing Spotify credentials" },
        { status: 500 }
      );
    }

    const userSnap = await adminDb.collection("users").doc(uid).get();
    const spotify = userSnap.data()?.integrations?.spotify;

    if (!spotify?.accessToken || !spotify?.refreshToken) {
      return Response.json({ error: "Spotify not connected" }, { status: 400 });
    }

    const spotifyApi = new SpotifyWebApi({
      clientId,
      clientSecret,
      redirectUri,
    });

    spotifyApi.setAccessToken(spotify.accessToken);
    spotifyApi.setRefreshToken(spotify.refreshToken);

    if (spotify.expiresAt && spotify.expiresAt < Date.now()) {
      const refreshed = await spotifyApi.refreshAccessToken();
      spotifyApi.setAccessToken(refreshed.body.access_token);
      await adminDb.collection("users").doc(uid).set(
        {
          integrations: {
            spotify: {
              accessToken: refreshed.body.access_token,
              expiresAt: Date.now() + refreshed.body.expires_in * 1000,
            },
          },
          updatedAt: new Date(),
        },
        { merge: true }
      );
    }

    const trackUris: string[] = [];
    for (const song of songs as SongInput[]) {
      const query = `${song.title} ${song.artist}`;
      const search = await spotifyApi.searchTracks(query, { limit: 1 });
      const item = search.body.tracks?.items?.[0];
      if (item?.uri) {
        trackUris.push(item.uri);
      }
    }

    const spotifyUserId = spotify.userId;
    if (!spotifyUserId) {
      return Response.json(
        { error: "Missing Spotify user id" },
        { status: 400 }
      );
    }

    const created = await spotifyApi.createPlaylist(spotifyUserId, playlistName, {
      description: "Generated by Bud",
      public: false,
    });

    if (trackUris.length > 0) {
      await spotifyApi.addTracksToPlaylist(created.body.id, trackUris);
    }

    return Response.json({
      playlistId: created.body.id,
      url: created.body.external_urls?.spotify ?? null,
    });
  } catch (error) {
    return Response.json({ error: "Spotify playlist creation failed" }, { status: 500 });
  }
}
