import { google } from "googleapis";

import { adminDb } from "@/lib/firebase/admin";
import { verifyUser } from "@/lib/firebase/verify";

type SongInput = { title: string; artist: string };

const CACHE_COLLECTION = "youtube_cache";
const CACHE_TTL_DAYS = 30;

function normalizeQuery(title: string, artist: string) {
  return `${title} ${artist}`.toLowerCase().replace(/\s+/g, " ").trim();
}

async function getCachedVideoId(query: string) {
  const docRef = adminDb.collection(CACHE_COLLECTION).doc(query);
  const snap = await docRef.get();
  if (!snap.exists) return null;
  const data = snap.data() as { videoId?: string; updatedAt?: Date };
  if (!data?.videoId || !data?.updatedAt) return null;
  const ageMs = Date.now() - new Date(data.updatedAt).getTime();
  const maxAge = CACHE_TTL_DAYS * 24 * 60 * 60 * 1000;
  if (ageMs > maxAge) return null;
  return data.videoId;
}

async function setCachedVideoId(query: string, videoId: string) {
  await adminDb.collection(CACHE_COLLECTION).doc(query).set(
    {
      videoId,
      updatedAt: new Date(),
    },
    { merge: true }
  );
}

async function sleep(ms: number) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

export async function POST(request: Request) {
  try {
    const uid = await verifyUser(request.headers.get("authorization"));
    const { playlistName, songs } = await request.json();

    if (!playlistName || !Array.isArray(songs)) {
      return Response.json({ error: "Missing payload" }, { status: 400 });
    }

    const clientId = process.env.YOUTUBE_CLIENT_ID;
    const clientSecret = process.env.YOUTUBE_CLIENT_SECRET;
    const redirectUri = process.env.NEXT_PUBLIC_YOUTUBE_REDIRECT_URI;

    if (!clientId || !clientSecret || !redirectUri) {
      return Response.json(
        { error: "Missing YouTube credentials" },
        { status: 500 }
      );
    }

    const userSnap = await adminDb.collection("users").doc(uid).get();
    const youtube = userSnap.data()?.integrations?.youtube;

    if (!youtube?.refreshToken) {
      return Response.json({ error: "YouTube not connected" }, { status: 400 });
    }

    const oauth2 = new google.auth.OAuth2(clientId, clientSecret, redirectUri);
    oauth2.setCredentials({
      refresh_token: youtube.refreshToken,
      access_token: youtube.accessToken,
      expiry_date: youtube.expiryDate,
    });

    const api = google.youtube({ version: "v3", auth: oauth2 });

    const created = await api.playlists.insert({
      part: ["snippet", "status"],
      requestBody: {
        snippet: {
          title: playlistName,
          description: "Generated by Bud",
        },
        status: { privacyStatus: "private" },
      },
    });

    const playlistId = created.data.id;
    if (!playlistId) {
      return Response.json(
        { error: "Playlist creation failed" },
        { status: 500 }
      );
    }

    const inRequestCache = new Map<string, string>();

    for (const song of songs as SongInput[]) {
      const q = normalizeQuery(song.title, song.artist);
      let videoId =
        inRequestCache.get(q) ?? (await getCachedVideoId(q));

      if (!videoId) {
        const search = await api.search.list({
          part: ["id"],
          q,
          maxResults: 1,
          type: ["video"],
        });
        videoId = search.data.items?.[0]?.id?.videoId ?? "";
        if (videoId) {
          inRequestCache.set(q, videoId);
          await setCachedVideoId(q, videoId);
        }
      }

      if (!videoId) continue;

      await api.playlistItems.insert({
        part: ["snippet"],
        requestBody: {
          snippet: {
            playlistId,
            resourceId: {
              kind: "youtube#video",
              videoId,
            },
          },
        },
      });

      // Gentle pacing to reduce rate-limit/quota spikes.
      await sleep(150);
    }

    return Response.json({
      playlistId,
      url: `https://music.youtube.com/playlist?list=${playlistId}`,
    });
  } catch (error) {
    const apiError = error as {
      message?: string;
      response?: { data?: { error?: { message?: string } } };
    };
    const details =
      process.env.NODE_ENV === "development"
        ? apiError.response?.data?.error?.message ??
          apiError.message ??
          String(error)
        : undefined;
    return Response.json(
      { error: "YouTube playlist creation failed", details },
      { status: 500 }
    );
  }
}
